services:
  database:
    container_name: db
    image: "postgres:latest"
    env_file:
      - .env
    networks:
      - app-network
    restart: on-failure
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - '4000:3001'
    restart: on-failure
    depends_on:
      - database
  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - app-network
    ports:
      - '8081:80'
    restart: on-failure
networks:
  app-network:
    driver: bridge
    internal: false
