FROM node:16-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY . .
RUN npm run build

FROM node:16-alpine as production
WORKDIR /app
RUN npm i -g pm2
COPY --from=builder /app/package*.json ./
RUN npm i --omit=dev
COPY --from=builder /app/dist ./dist/
COPY ecosystem.config.js ./
EXPOSE 3001
CMD ["pm2-runtime", "ecosystem.config.js"] 
